development:
  user: fedoraAdmin
  password: fedoraPassword
  url: http://127.0.0.1:8984/fedora4/rest
  base_path: ""
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:<%= ENV['FCREPO_TEST_PORT'] || 8986 %>/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraPassword
  url: http://127.0.0.1:8984/fedora4/rest
  base_path: ""

