# This is a sample config file that points to a solr server for each environment
development:
  url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/hydra-development
test:
  url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8985 %>/solr/hydra-test
  read_timeout: 240
  open_timeout: 240
production:
  url: http://127.0.0.1:8983/solr/avalon
